### ISSUE TITLE
minZoom and maxZoom not working

### ISSUE THREAD

**Issue by ervibern** [TiagoCavalcante/r3f-native-orbitcontrols#15]
Hi, thanks for this handy library for simple orbit controls - works for me on iOS physical device. The only thing I didn't manage to get working is zoom - tried multiple values (0.1, 1, 10, 100, etc) but they don't seem to change the zooming ability. I couldn't find how you implemented this in the library as it says maxZoom: infinity. 

```
<Canvas shadows camera={camera}>
  <ambientLight />
  <pointLight intensity={LIGHT_INTENSITY} position={LIGHT_POSITION} />
  <OrbitControls enablePan={false} enableZoom maxZoom={1} rotateSpeed={0.5} />
  <Suspense fallback={null}>
    <Torus />
  </Suspense>
</Canvas>

**Comment by TiagoCavalcante** [comment]
@ervibern Thanks for using the library and creating the issue!

Before #17 the options `minZoom` and `maxZoom` were not used, instead of them there were `minDistance` and `maxDistance` (even though `minZoom` and `maxZoom` were mentioned in the documentation).
Now I'm publish a new version with the fix

**Comment by ervibern** [comment]
Great @TiagoCavalcante - thanks for that. Awesome work!
