### ISSUE TITLE
Controls not working on IOS 16 and very lagi on IOS 15

### ISSUE THREAD

**Issue by StjepanSuton** [TiagoCavalcante/r3f-native-orbitcontrols#8]
Working fine on android but does not work at all on IOS 16 and very lagy on 15

    <View style={{ flex: 1 }} {...events}>
      <Canvas gl={{ physicallyCorrectLights: true }} camera={{ position: [0, 0, 10], fov: 36 }}>
        <color attach="background" args={[0xe2f4df]} />
        <OrbitControls />
        <ambientLight intensity={1} />
        <Suspense>
          <Port url={portModel} />
        </Suspense>
      </Canvas>
    </View>

```
{
  "main": "node_modules/expo/AppEntry.js",
  "private": true,
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web",
    "eject": "expo eject"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3"
  },
  "dependencies": {
    "@react-three/drei": "^9.34.3",
    "@react-three/fiber": "^8.8.9",
    "expo": "^46.0.15",
    "expo-gl": "~11.4.0",
    "r3f-native-orbitcontrols": "^1.0.4",
    "react": "18.0.0",
    "react-native": "0.69.6",
    "three": "^0.145.0"
  }
}
```

**Comment by TiagoCavalcante** [comment]
Hi @StjepanSuton, thanks for using the library and creating the issue, unfortunately I couldn't reproduce this in my iPhone 12 with iOS 16.2, so I'll have to ask some questions in order to fix this:
1. Which are your phone models (or iOS emulator)?
2. Is your code the same for Android and iOS?
3. What happens when you remove the orbit controls?
4. What happens when you rotate the camera manually (without this library)?

**Comment by StjepanSuton** [comment]
Hi haven't used RN in a while and it seems the issue was with the emulators, tested it on a few other IOS and Android devices and it works fine.
